name: Build

# Trigger when a pull request is received
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        include:
          - os: ubuntu-latest
    steps:  
    - name: Checkout the code
      uses: actions/checkout@v3
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the Pico Toolchain
      run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib
    
    - name: Install AtariST Toolkit Docker image
      run: curl -sL https://github.com/sidecartridge/atarist-toolkit-docker/releases/download/v1.0.0/install_atarist_toolkit_docker.sh | bash

    - name: Run - remove interactive
      run: sed -i 's/-it//' /usr/local/bin/stcmd

    - name: Run - Build PICO_W release version
      run: ./build.sh pico_w release image

    - name: Run - Build PICO_W debug version
      run: ./build.sh pico_w debug
